<a href="https://colab.research.google.com/github/mahamtaqi3-cloud/Python-libraries-teaching-materials/blob/main/Introduction_to_NumPy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to NumPy in Python

NumPy (Numerical Python) is a Python library used for numerical computing. Its main feature is the NumPy array, which allows you to store and perform operations on large amounts of numerical data efficiently.

1. Import NumPy

In [ ]:
import numpy as np

2. Creating an Array

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


In [ ]:
import numpy as np
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


3. Array Operations

Unlike normal Python lists, NumPy arrays allow mathematical operations directly.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


4. Useful NumPy Functions

In [ ]:
numbers = np.array([10, 20, 30, 40, 50])

print(np.mean(numbers))   # Average
print(np.max(numbers))    # Maximum
print(np.min(numbers))    # Minimum
print(np.sum(numbers))    # Sum

30.0
50
10
150


5. Creating Special Arrays

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

6. 2D Arrays

NumPy is particularly useful for working with matrices and tables.

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

[[1 2 3]
 [4 5 6]]


You can check its dimensions:

In [ ]:
print(matrix.shape)

(2, 3)


This means 2 rows × 3 columns.

7. Accessing Elements

In [ ]:
print(matrix[0, 1])

2


*Python* uses zero-based indexing, so [0, 1] means first row, second column.

Why is NumPy important for Computer Science?

NumPy is important because it makes numerical and data-based computing faster, easier, and more efficient in Python.

Key reasons:
Fast numerical calculations
NumPy performs mathematical operations much faster than regular Python lists, especially with large datasets.
Efficient data storage
NumPy arrays use memory efficiently, making them useful for handling thousands or millions of values.
Supports mathematical operations
It provides functions for:
Mean, median, standard deviation
Matrix multiplication
Linear algebra
Statistics
Random number generation
Foundation for Data Science & AI
Libraries such as Pandas, SciPy, Scikit-learn, and many machine-learning tools work closely with NumPy.
Machine Learning
Data, model parameters, weights, and mathematical computations are often represented as NumPy arrays.
Computer Vision & Image Processing
Images can be represented as numerical arrays, allowing computers to manipulate pixels using NumPy.
Scientific Computing
Researchers use NumPy for simulations, experiments, mathematical modeling, and analysis of large datasets.

Simple example

Without NumPy:

In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]

With NumPy:

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


Why NumPy is important for bioinformatics

For your molecular biology, genetics, and bioinformatics projects, NumPy is useful for handling:

DNA/protein numerical representations
Gene-expression matrices
Sequence-analysis data
Statistical calculations
Machine-learning datasets
Image and hyperspectral data
Large biological datasets

In simple terms:

NumPy gives Python fast and powerful tools for working with numerical arrays and mathematical operations.

NumPy in Bioinformatics — Simple Example

A common bioinformatics task is analyzing DNA sequences. NumPy can represent numerical information from DNA and perform calculations efficiently.

For example, suppose we want to calculate the GC content of a DNA sequence.

In [ ]:
import numpy as np

# DNA sequence
sequence = "ATGCGATCGATCGC"

# Convert sequence into an array
dna = np.array(list(sequence))

print(dna)

['A' 'T' 'G' 'C' 'G' 'A' 'T' 'C' 'G' 'A' 'T' 'C' 'G' 'C']


Now calculate the number of G and C bases:

In [ ]:
gc_count = np.sum((dna == 'G') | (dna == 'C'))

gc_content = (gc_count / len(dna)) * 100

print("GC Content:", gc_content, "%")

GC Content: 57.14285714285714 %


Another important example: Gene Expression

Suppose we have expression values for a gene across several samples:

In [ ]:
expression = np.array([12, 15, 18, 20, 25])

print("Mean expression:", np.mean(expression))
print("Maximum:", np.max(expression))
print("Minimum:", np.min(expression))

Mean expression: 18.0
Maximum: 25
Minimum: 12


This can help researchers analyze gene-expression patterns across samples.

Why this matters in bioinformatics

NumPy is useful for:

🧬 DNA/RNA sequence analysis
🧪 Gene-expression data
📊 Statistical analysis
🧫 Genomic datasets
🤖 Machine-learning preprocessing
🧮 Biological simulations
🔬 Matrix-based biological calculations